// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuCzrcnKPAIjN7O4lrGbugkXVn22kbcII',
    appId: '1:470794303211:web:7cf8fc56ebc6079fe6b0ae',
    messagingSenderId: '470794303211',
    projectId: 'pasal-f',
    authDomain: 'pasal-f.firebaseapp.com',
    storageBucket: 'pasal-f.appspot.com',
    measurementId: 'G-7G89KX5RG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZudlPT2GJZKQhC5GyArzzv-5EgBpHGlU',
    appId: '1:470794303211:android:c9a894495bbebe95e6b0ae',
    messagingSenderId: '470794303211',
    projectId: 'pasal-f',
    storageBucket: 'pasal-f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAczmyekVYGRpHTejkcxzxgJWdZerg0s_o',
    appId: '1:470794303211:ios:e0b6f53f8d5a9cb6e6b0ae',
    messagingSenderId: '470794303211',
    projectId: 'pasal-f',
    storageBucket: 'pasal-f.appspot.com',
    iosClientId: '470794303211-6ucq5hhjdf96q5fab6r3ehjei3caqg6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAczmyekVYGRpHTejkcxzxgJWdZerg0s_o',
    appId: '1:470794303211:ios:e0b6f53f8d5a9cb6e6b0ae',
    messagingSenderId: '470794303211',
    projectId: 'pasal-f',
    storageBucket: 'pasal-f.appspot.com',
    iosClientId: '470794303211-6ucq5hhjdf96q5fab6r3ehjei3caqg6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasal',
  );
}
